// user
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOADING_USER = "LOADING_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SET_ERROR = "SET_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
// messages
export const ADD_CHANNEL = "ADD_CHANNELS";
export const SET_CHANNELS = "SET_CHANNELS";
export const SET_CURRENT_CHANNEL = "SET_CURRENT_CHANNEL";
export const SET_MSG_ERROR = "SET_MSG_ERROR";
export const LOADING_MSGS = "LOADING_MSGS";
export const SET_CURRENT_MESSAGES = "SET_CURRENT_MESSAGES";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const CLEAR_SEARCH_TERM = "CLEAR_SEARCH_TERM";
export const SET_PRIVATE_CHANNEL = "SET_PRIVATE_CHANNEL";
